# Header
menu:
  Home: /
  Archives: /archives
  About: /about
# rss: /atom.xml

# Content
excerpt_link:  .  .  .

# Favicon
# favicon: /favicon.ico

# Settings toggle
settings: true

# Code CSS toggle
highlight: true

# Word count (needs hexo-wordcount)
word_count: true

# Google Analytics
google_analytics:
  enable: false
  acct: "UA-000000000-0"

# IntenseDebate ID
intensedebate:
  enable: false
  acct: "00000000000000000000000000000000"
